language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install numpy coverage

script: coverage run -m unittest discover
after_success:
  - bash <(curl -s https://codecov.io/bash) -f .coverage || echo "Codecov did not collect coverage reports"