language: python
python:
  - "3.9"
# command to install dependencies
install:
  - pip install numpy coverage

script:
  - coverage run -m unittest discover
  - coverage xml
after_success:
  - bash <(curl -s https://codecov.io/bash) -f coverage.xml || echo "Codecov did not collect coverage reports"