from .software import Software
from .bloco import Bloco
from .conteudo_bloco import ConteudoBloco
from .lista_variaveis import ListaVariaveis
from .lista_comandos import ListaComandos
from .declaracao_de_variavel import DeclaracaoDeVariavel
from .comando import Comando
from .lista_ids import ListaIDs
from .mais_de_um_id import MaisDeUmID
from .cmd_selecao import CmdSelecao
from .com_else import ComElse
from .cmd_repeticao import CmdRepeticao
from .cmd_repeticao_while import CmdRepeticaoWhile
from .cmd_repeticao_do_until import CmdRepeticaoDoUntil
from .cmd_atribuicao import CmdAtribuicao
from .condicao import Condicao
from .condicao_linha import CondicaoLinha
from .expressao import Expressao
from .expressao_linha import ExpressaoLinha
from .id_ou_constante import IdOuConstante
